/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/auth/_layout'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AuthLayoutRegisterImport } from './routes/auth/_layout/register'
import { Route as AuthLayoutLoginImport } from './routes/auth/_layout/login'
import { Route as AppMProjectsIndexImport } from './routes/_app/m/projects/index'
import { Route as AppDProjectsIndexImport } from './routes/_app/d/projects/index'
import { Route as AppMProjectsProjectIdLayoutImport } from './routes/_app/m/projects/$projectId/_layout'
import { Route as AppDProjectsProjectIdLayoutImport } from './routes/_app/d/projects/$projectId/_layout'
import { Route as AppMProjectsProjectIdLayoutIndexImport } from './routes/_app/m/projects/$projectId/_layout/index'
import { Route as AppDProjectsProjectIdLayoutIndexImport } from './routes/_app/d/projects/$projectId/_layout/index'
import { Route as AppMProjectsProjectIdLayoutDevicesImport } from './routes/_app/m/projects/$projectId/_layout/devices'
import { Route as AppDProjectsProjectIdLayoutGatewaysImport } from './routes/_app/d/projects/$projectId/_layout/gateways'
import { Route as AppDProjectsProjectIdLayoutDevicesImport } from './routes/_app/d/projects/$projectId/_layout/devices'
import { Route as AppMProjectsProjectIdLayoutDashboardIndexImport } from './routes/_app/m/projects/$projectId/_layout/dashboard/index'
import { Route as AppDProjectsProjectIdLayoutDashboardIndexImport } from './routes/_app/d/projects/$projectId/_layout/dashboard/index'
import { Route as AppMProjectsProjectIdLayoutDashboardEditImport } from './routes/_app/m/projects/$projectId/_layout/dashboard/edit'
import { Route as AppDProjectsProjectIdLayoutDashboardEditImport } from './routes/_app/d/projects/$projectId/_layout/dashboard/edit'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()
const AppMProjectsProjectIdImport = createFileRoute(
  '/_app/m/projects/$projectId',
)()
const AppDProjectsProjectIdImport = createFileRoute(
  '/_app/d/projects/$projectId',
)()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AuthLayoutRegisterRoute = AuthLayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AppMProjectsProjectIdRoute = AppMProjectsProjectIdImport.update({
  path: '/m/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

const AppDProjectsProjectIdRoute = AppDProjectsProjectIdImport.update({
  path: '/d/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

const AppMProjectsIndexRoute = AppMProjectsIndexImport.update({
  path: '/m/projects/',
  getParentRoute: () => AppRoute,
} as any)

const AppDProjectsIndexRoute = AppDProjectsIndexImport.update({
  path: '/d/projects/',
  getParentRoute: () => AppRoute,
} as any)

const AppMProjectsProjectIdLayoutRoute =
  AppMProjectsProjectIdLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AppMProjectsProjectIdRoute,
  } as any)

const AppDProjectsProjectIdLayoutRoute =
  AppDProjectsProjectIdLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AppDProjectsProjectIdRoute,
  } as any)

const AppMProjectsProjectIdLayoutIndexRoute =
  AppMProjectsProjectIdLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppMProjectsProjectIdLayoutRoute,
  } as any)

const AppDProjectsProjectIdLayoutIndexRoute =
  AppDProjectsProjectIdLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppDProjectsProjectIdLayoutRoute,
  } as any)

const AppMProjectsProjectIdLayoutDevicesRoute =
  AppMProjectsProjectIdLayoutDevicesImport.update({
    path: '/devices',
    getParentRoute: () => AppMProjectsProjectIdLayoutRoute,
  } as any)

const AppDProjectsProjectIdLayoutGatewaysRoute =
  AppDProjectsProjectIdLayoutGatewaysImport.update({
    path: '/gateways',
    getParentRoute: () => AppDProjectsProjectIdLayoutRoute,
  } as any)

const AppDProjectsProjectIdLayoutDevicesRoute =
  AppDProjectsProjectIdLayoutDevicesImport.update({
    path: '/devices',
    getParentRoute: () => AppDProjectsProjectIdLayoutRoute,
  } as any)

const AppMProjectsProjectIdLayoutDashboardIndexRoute =
  AppMProjectsProjectIdLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AppMProjectsProjectIdLayoutRoute,
  } as any)

const AppDProjectsProjectIdLayoutDashboardIndexRoute =
  AppDProjectsProjectIdLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AppDProjectsProjectIdLayoutRoute,
  } as any)

const AppMProjectsProjectIdLayoutDashboardEditRoute =
  AppMProjectsProjectIdLayoutDashboardEditImport.update({
    path: '/dashboard/edit',
    getParentRoute: () => AppMProjectsProjectIdLayoutRoute,
  } as any)

const AppDProjectsProjectIdLayoutDashboardEditRoute =
  AppDProjectsProjectIdLayoutDashboardEditImport.update({
    path: '/dashboard/edit',
    getParentRoute: () => AppDProjectsProjectIdLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_layout/login': {
      id: '/auth/_layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/_layout/register': {
      id: '/auth/_layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/d/projects/': {
      id: '/_app/d/projects/'
      path: '/d/projects'
      fullPath: '/d/projects'
      preLoaderRoute: typeof AppDProjectsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/m/projects/': {
      id: '/_app/m/projects/'
      path: '/m/projects'
      fullPath: '/m/projects'
      preLoaderRoute: typeof AppMProjectsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/d/projects/$projectId': {
      id: '/_app/d/projects/$projectId'
      path: '/d/projects/$projectId'
      fullPath: '/d/projects/$projectId'
      preLoaderRoute: typeof AppDProjectsProjectIdImport
      parentRoute: typeof AppImport
    }
    '/_app/d/projects/$projectId/_layout': {
      id: '/_app/d/projects/$projectId/_layout'
      path: '/d/projects/$projectId'
      fullPath: '/d/projects/$projectId'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutImport
      parentRoute: typeof AppDProjectsProjectIdRoute
    }
    '/_app/m/projects/$projectId': {
      id: '/_app/m/projects/$projectId'
      path: '/m/projects/$projectId'
      fullPath: '/m/projects/$projectId'
      preLoaderRoute: typeof AppMProjectsProjectIdImport
      parentRoute: typeof AppImport
    }
    '/_app/m/projects/$projectId/_layout': {
      id: '/_app/m/projects/$projectId/_layout'
      path: '/m/projects/$projectId'
      fullPath: '/m/projects/$projectId'
      preLoaderRoute: typeof AppMProjectsProjectIdLayoutImport
      parentRoute: typeof AppMProjectsProjectIdRoute
    }
    '/_app/d/projects/$projectId/_layout/devices': {
      id: '/_app/d/projects/$projectId/_layout/devices'
      path: '/devices'
      fullPath: '/d/projects/$projectId/devices'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutDevicesImport
      parentRoute: typeof AppDProjectsProjectIdLayoutImport
    }
    '/_app/d/projects/$projectId/_layout/gateways': {
      id: '/_app/d/projects/$projectId/_layout/gateways'
      path: '/gateways'
      fullPath: '/d/projects/$projectId/gateways'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutGatewaysImport
      parentRoute: typeof AppDProjectsProjectIdLayoutImport
    }
    '/_app/m/projects/$projectId/_layout/devices': {
      id: '/_app/m/projects/$projectId/_layout/devices'
      path: '/devices'
      fullPath: '/m/projects/$projectId/devices'
      preLoaderRoute: typeof AppMProjectsProjectIdLayoutDevicesImport
      parentRoute: typeof AppMProjectsProjectIdLayoutImport
    }
    '/_app/d/projects/$projectId/_layout/': {
      id: '/_app/d/projects/$projectId/_layout/'
      path: '/'
      fullPath: '/d/projects/$projectId/'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutIndexImport
      parentRoute: typeof AppDProjectsProjectIdLayoutImport
    }
    '/_app/m/projects/$projectId/_layout/': {
      id: '/_app/m/projects/$projectId/_layout/'
      path: '/'
      fullPath: '/m/projects/$projectId/'
      preLoaderRoute: typeof AppMProjectsProjectIdLayoutIndexImport
      parentRoute: typeof AppMProjectsProjectIdLayoutImport
    }
    '/_app/d/projects/$projectId/_layout/dashboard/edit': {
      id: '/_app/d/projects/$projectId/_layout/dashboard/edit'
      path: '/dashboard/edit'
      fullPath: '/d/projects/$projectId/dashboard/edit'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutDashboardEditImport
      parentRoute: typeof AppDProjectsProjectIdLayoutImport
    }
    '/_app/m/projects/$projectId/_layout/dashboard/edit': {
      id: '/_app/m/projects/$projectId/_layout/dashboard/edit'
      path: '/dashboard/edit'
      fullPath: '/m/projects/$projectId/dashboard/edit'
      preLoaderRoute: typeof AppMProjectsProjectIdLayoutDashboardEditImport
      parentRoute: typeof AppMProjectsProjectIdLayoutImport
    }
    '/_app/d/projects/$projectId/_layout/dashboard/': {
      id: '/_app/d/projects/$projectId/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/d/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppDProjectsProjectIdLayoutDashboardIndexImport
      parentRoute: typeof AppDProjectsProjectIdLayoutImport
    }
    '/_app/m/projects/$projectId/_layout/dashboard/': {
      id: '/_app/m/projects/$projectId/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/m/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppMProjectsProjectIdLayoutDashboardIndexImport
      parentRoute: typeof AppMProjectsProjectIdLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppProfileIndexRoute,
    AppDProjectsIndexRoute,
    AppMProjectsIndexRoute,
    AppDProjectsProjectIdRoute: AppDProjectsProjectIdRoute.addChildren({
      AppDProjectsProjectIdLayoutRoute:
        AppDProjectsProjectIdLayoutRoute.addChildren({
          AppDProjectsProjectIdLayoutDevicesRoute,
          AppDProjectsProjectIdLayoutGatewaysRoute,
          AppDProjectsProjectIdLayoutIndexRoute,
          AppDProjectsProjectIdLayoutDashboardEditRoute,
          AppDProjectsProjectIdLayoutDashboardIndexRoute,
        }),
    }),
    AppMProjectsProjectIdRoute: AppMProjectsProjectIdRoute.addChildren({
      AppMProjectsProjectIdLayoutRoute:
        AppMProjectsProjectIdLayoutRoute.addChildren({
          AppMProjectsProjectIdLayoutDevicesRoute,
          AppMProjectsProjectIdLayoutIndexRoute,
          AppMProjectsProjectIdLayoutDashboardEditRoute,
          AppMProjectsProjectIdLayoutDashboardIndexRoute,
        }),
    }),
  }),
  AuthRoute: AuthRoute.addChildren({
    AuthLayoutRoute: AuthLayoutRoute.addChildren({
      AuthLayoutLoginRoute,
      AuthLayoutRegisterRoute,
    }),
  }),
})

/* prettier-ignore-end */
