/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as AppProjectsIndexImport } from './routes/_app/projects/index'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AuthAuthRegisterImport } from './routes/auth/_auth/register'
import { Route as AuthAuthLoginImport } from './routes/auth/_auth/login'
import { Route as AppProjectsProjectIdProjectIdImport } from './routes/_app/projects/$projectId/_$projectId'
import { Route as AppProjectsProjectIdProjectIdIndexImport } from './routes/_app/projects/$projectId/_$projectId/index'
import { Route as AppProjectsProjectIdProjectIdGatewaysImport } from './routes/_app/projects/$projectId/_$projectId/gateways'
import { Route as AppProjectsProjectIdProjectIdDevicesImport } from './routes/_app/projects/$projectId/_$projectId/devices'
import { Route as AppProjectsProjectIdProjectIdDashboardIndexImport } from './routes/_app/projects/$projectId/_$projectId/dashboard/index'
import { Route as AppProjectsProjectIdProjectIdDashboardEditImport } from './routes/_app/projects/$projectId/_$projectId/dashboard/edit'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()
const AppProjectsProjectIdImport = createFileRoute(
  '/_app/projects/$projectId',
)()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const AppProjectsProjectIdRoute = AppProjectsProjectIdImport.update({
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

const AppProjectsIndexRoute = AppProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AppProjectsProjectIdProjectIdRoute =
  AppProjectsProjectIdProjectIdImport.update({
    id: '/_$projectId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)

const AppProjectsProjectIdProjectIdIndexRoute =
  AppProjectsProjectIdProjectIdIndexImport.update({
    path: '/',
    getParentRoute: () => AppProjectsProjectIdProjectIdRoute,
  } as any)

const AppProjectsProjectIdProjectIdGatewaysRoute =
  AppProjectsProjectIdProjectIdGatewaysImport.update({
    path: '/gateways',
    getParentRoute: () => AppProjectsProjectIdProjectIdRoute,
  } as any)

const AppProjectsProjectIdProjectIdDevicesRoute =
  AppProjectsProjectIdProjectIdDevicesImport.update({
    path: '/devices',
    getParentRoute: () => AppProjectsProjectIdProjectIdRoute,
  } as any)

const AppProjectsProjectIdProjectIdDashboardIndexRoute =
  AppProjectsProjectIdProjectIdDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AppProjectsProjectIdProjectIdRoute,
  } as any)

const AppProjectsProjectIdProjectIdDashboardEditRoute =
  AppProjectsProjectIdProjectIdDashboardEditImport.update({
    path: '/dashboard/edit',
    getParentRoute: () => AppProjectsProjectIdProjectIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth/login': {
      id: '/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/register': {
      id: '/auth/_auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthAuthImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdImport
      parentRoute: typeof AppImport
    }
    '/_app/projects/$projectId/_$projectId': {
      id: '/_app/projects/$projectId/_$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/_$projectId/devices': {
      id: '/_app/projects/$projectId/_$projectId/devices'
      path: '/devices'
      fullPath: '/projects/$projectId/devices'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdDevicesImport
      parentRoute: typeof AppProjectsProjectIdProjectIdImport
    }
    '/_app/projects/$projectId/_$projectId/gateways': {
      id: '/_app/projects/$projectId/_$projectId/gateways'
      path: '/gateways'
      fullPath: '/projects/$projectId/gateways'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdGatewaysImport
      parentRoute: typeof AppProjectsProjectIdProjectIdImport
    }
    '/_app/projects/$projectId/_$projectId/': {
      id: '/_app/projects/$projectId/_$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdIndexImport
      parentRoute: typeof AppProjectsProjectIdProjectIdImport
    }
    '/_app/projects/$projectId/_$projectId/dashboard/edit': {
      id: '/_app/projects/$projectId/_$projectId/dashboard/edit'
      path: '/dashboard/edit'
      fullPath: '/projects/$projectId/dashboard/edit'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdDashboardEditImport
      parentRoute: typeof AppProjectsProjectIdProjectIdImport
    }
    '/_app/projects/$projectId/_$projectId/dashboard/': {
      id: '/_app/projects/$projectId/_$projectId/dashboard/'
      path: '/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppProjectsProjectIdProjectIdDashboardIndexImport
      parentRoute: typeof AppProjectsProjectIdProjectIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AppRoute: AppRoute.addChildren({
    AppProfileIndexRoute,
    AppProjectsIndexRoute,
    AppProjectsProjectIdRoute: AppProjectsProjectIdRoute.addChildren({
      AppProjectsProjectIdProjectIdRoute:
        AppProjectsProjectIdProjectIdRoute.addChildren({
          AppProjectsProjectIdProjectIdDevicesRoute,
          AppProjectsProjectIdProjectIdGatewaysRoute,
          AppProjectsProjectIdProjectIdIndexRoute,
          AppProjectsProjectIdProjectIdDashboardEditRoute,
          AppProjectsProjectIdProjectIdDashboardIndexRoute,
        }),
    }),
  }),
  AuthRoute: AuthRoute.addChildren({
    AuthAuthRoute: AuthAuthRoute.addChildren({
      AuthAuthLoginRoute,
      AuthAuthRegisterRoute,
    }),
  }),
})

/* prettier-ignore-end */
